---

- name: Ensure vault.hcl
  template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0640'
  notify: Start vault.service

- name: Ensure vault.service
  template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    mode: '0644'
  notify: Start vault.service

