---

all:
  hosts:
    root:
      ansible_port: 2222
    intermediate:
      ansible_port: 2223
    issuing:
      ansible_port: 2224
  vars:
    ansible_host: 127.0.0.1
    ansible_ssh_common_args: -o StrictHostKeyChecking=no


openssl:
  hosts:
    root:

vault:
  hosts:
    intermediate:
    issuing:
  vars:
    vault_url: "https://releases.hashicorp.com/vault"
    vault_version: "1.5.0"
    vault_keep_zip: true
    vault_tls_disable: true
